TOP := "r24bb_top"

RTL?=
RTL+=$(ROOTDIR)/hdl/adc_channel.sv
RTL+=$(ROOTDIR)/hdl/adc_channel_regs.sv
RTL+=$(ROOTDIR)/hdl/aic3204_if.sv
RTL+=$(ROOTDIR)/hdl/cross_interp.sv
RTL+=$(ROOTDIR)/hdl/dac_channel.sv
RTL+=$(ROOTDIR)/hdl/dac_channel_regs.sv
RTL+=$(ROOTDIR)/hdl/ddac.sv
RTL+=$(ROOTDIR)/hdl/dds.sv
RTL+=$(ROOTDIR)/hdl/divlut.sv
RTL+=$(ROOTDIR)/hdl/fir_cell.sv
RTL+=$(ROOTDIR)/hdl/fir_filter.sv
RTL+=$(ROOTDIR)/hdl/fm_demod.sv
RTL+=$(ROOTDIR)/hdl/ft601_if.sv
RTL+=$(ROOTDIR)/hdl/i2c_basic.sv
RTL+=$(ROOTDIR)/hdl/i2c_ioexp.sv
RTL+=$(ROOTDIR)/hdl/max19506_if.sv
RTL+=$(ROOTDIR)/hdl/max19506_serial_if.sv
RTL+=$(ROOTDIR)/hdl/max5851_if.sv
RTL+=$(ROOTDIR)/hdl/prbs.sv
RTL+=$(ROOTDIR)/hdl/r24bb_top.sv
RTL+=$(ROOTDIR)/hdl/regs.sv
RTL+=$(ROOTDIR)/hdl/sigstat.sv