webtalk_init -webtalk_dir D:/Projects/Baseband/radio24bb/usb_mc/usb_mc.sim/sim_1/behav/xsim/xsim.dir/tb_mcfifo_wr_buf_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 24 22:50:25 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4b2e513a-d42c-4f24-9949-7953eeeb1932" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5e95b51fec904883ab7d2a4eb310eb4f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "78" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 1700X Eight-Core Processor         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "6" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "179 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "21 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "394" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "33" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.26_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "62760_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2779855409 -regid "" -xml D:/Projects/Baseband/radio24bb/usb_mc/usb_mc.sim/sim_1/behav/xsim/xsim.dir/tb_mcfifo_wr_buf_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Projects/Baseband/radio24bb/usb_mc/usb_mc.sim/sim_1/behav/xsim/xsim.dir/tb_mcfifo_wr_buf_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Projects/Baseband/radio24bb/usb_mc/usb_mc.sim/sim_1/behav/xsim/xsim.dir/tb_mcfifo_wr_buf_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
